"""Generate a LaTeX snippet for the Introduction use-case box.

The snippet is designed to work with the existing IEEEtran draft and only
relies on packages already loaded in paper_draft/main.tex (notably xcolor
and tikz). It does not modify the main manuscript; it only writes a new
standalone .tex fragment that can later be inserted with \input{...}.
"""

from __future__ import annotations

import argparse
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO / "paper_draft" / "intro_use_case_box.tex"


BOX_TEMPLATE = r"""% Auto-generated by paper_draft/scripts/build_intro_use_case_box.py
% Suggested insertion point: immediately after the problem-setting paragraph in the Introduction.
\begin{center}
\begin{tikzpicture}
\node[
  draw=black!18,
  fill=cyan!3,
  rounded corners=5pt,
  inner xsep=9pt,
  inner ysep=8pt,
  text width=0.96\columnwidth,
  align=left
] {{
{{\bfseries\small Use Case: Lag Auditing in Country-Level Panels}}\\[3pt]
{{\footnotesize
\textbf{{Input.}} Annual country-level panel sequences with entity-level proxy vectors describing development capacity, institutional conditions, or absorptive foundations.\\[2pt]
\textbf{{Output.}} Effective-lag metrics, non-degenerate $k_i^*$, stratifier-alignment diagnostics, and a verdict matrix for mechanism auditing.\\[2pt]
\textbf{{Primary users.}} Economic-growth researchers, energy-policy analysts, and data-science auditors working with cross-country panel data.\\[2pt]
\textbf{{Decision scope.}} Detect whether structured lag heterogeneity exists and whether it aligns with observable entity conditions, rather than issuing direct causal policy prescriptions.
}}
}};
\end{tikzpicture}
\end{center}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the Introduction use-case box snippet.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path of the generated LaTeX snippet.",
    )
    return parser.parse_args()


def build_snippet() -> str:
    return BOX_TEMPLATE


def main() -> int:
    args = parse_args()
    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_snippet(), encoding="utf-8")
    print(f"Generated: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())